name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
        run: npm install

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: pip3 install -r astrograph/requirements.txt
      
      - name: Build Telescope
        run: npm run build
