name: Build/release

on:  
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            build: electron:mac
          - os: ubuntu-latest
            build: electron:linux
          - os: windows-latest
            build: electron:windows

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          npm install
          pip3 install -r astrograph/requirements.txt

      - name: Build Telescope
        run: npm run ${{ matrix.build }}